CREATE TABLE [Reporting].[Periodicity]
(
	[ID] INT NOT NULL , 
    [NAME] VARCHAR(100) NOT NULL, 
    [DESCRIPTION] VARCHAR(1000) NULL, 
    CONSTRAINT [PK_REPORTING_PERIODICITY] PRIMARY KEY ([ID]), 
    CONSTRAINT [UK_REPORTIGN_PERIODICITY__NAME] UNIQUE ([NAME])
)
