CREATE TABLE [Reporting].[ReportHistory]
(
	[ID] INT NOT NULL IDENTITY , 
	[REPORTID] INT NOT NULL, 
    [NAME] VARCHAR(100) NOT NULL, 
	[DESCRIPTION] VARCHAR(2000) NOT NULL, 
    [SETTINGS] NCHAR(10) NULL, 
	[FL_DISABLED] BIT NOT NULL DEFAULT 0,
	[PERIODICITY] VARCHAR(20) NULL,
	[REPORTTYPE] VARCHAR(50) NOT NULL,
	[CREATED] DATETIME NOT NULL DEFAULT GETDATE(), 
    [CREATOR] VARCHAR(100) NOT NULL DEFAULT USER, 
    [CHANGED] DATETIME NULL, 
    [CHANGER] VARCHAR(100) NULL,

    [HCREATED] DATETIME NOT NULL DEFAULT GETDATE(), 
    CONSTRAINT [PK_REPORTING_REPORTHISTORY] PRIMARY KEY ([ID]), 
)
