CREATE TABLE [Reporting].[ReportUser]
(
	[REPORTID] INT NOT NULL , 
    [USERID] INT NOT NULL, 
    CONSTRAINT [PK_REPORTING_REPORTUSER] PRIMARY KEY ([REPORTID], [USERID]), 
    CONSTRAINT [FK_REPORTING_REPORTUSER__REPROTID] FOREIGN KEY ([REPORTID]) REFERENCES [Reporting].[Report]([ID]), 
    CONSTRAINT [FK_REPORTING_REPORTUSER__USERID] FOREIGN KEY ([USERID]) REFERENCES [Reporting].[User]([ID])
)
