CREATE TABLE [Reporting].[UserNet]
(
	[USERID] INT NOT NULL , 
    [NETPATH] VARCHAR(200) NOT NULL, 
    CONSTRAINT [PK_REPOTING_USERNET] PRIMARY KEY ([USERID], [NETPATH]), 
    CONSTRAINT [FK_REPORTING_USERNET__USERID] FOREIGN KEY ([USERID]) REFERENCES [Reporting].[User]([ID])
)
