--	---------------------------------------------------------------------------------------------------------------------------
--		
--		2019-03-19, ЗОЛОТЕНКО М.
--		
--		ДОВІДНИК КОРИСТУВАЧІВ
--	
--	
CREATE TABLE [Reporting].[User]
(
	[ID] INT NOT NULL  IDENTITY, 
	[EMAIL] VARCHAR(100) NOT NULL,
	[SURNAME] VARCHAR(100) NOT NULL,
    [NAME] VARCHAR(100) NULL, 
	[PATRONYMIC] VARCHAR(100) NULL,
	[LOGIN] VARCHAR(100) NULL,
	[INN] VARCHAR(50) NULL,
	[DIVISION] VARCHAR(255) NULL,
	[POSITION] VARCHAR(100) NULL,
	[DEPARTMENT] VARCHAR(100) NULL,
	[BANK_NFS] VARCHAR(20) NULL,
	[NAME_NET] VARCHAR(100) NULL,

	[FL_FIRED] BIT NULL DEFAULT 0, 

    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(), 
    [CREATOR] VARCHAR(100) NOT NULL DEFAULT USER, 
    [CHANGED] DATETIME NULL, 
    [CHANGER] VARCHAR(100) NULL, 

    CONSTRAINT [PK_REPORTING_USER] PRIMARY KEY ([ID]), 
    CONSTRAINT [UQ_REPORTING_USER__EMAIL] UNIQUE ([EMAIL])
)

GO

CREATE TRIGGER [Reporting].[TRG_REPORTING_USER]
    ON [Reporting].[User]
    FOR DELETE, UPDATE
    AS
    BEGIN
        SET NOCOUNT ON;

		--	ЯКЩО DELETE
		IF NOT EXISTS(SELECT 1 FROM inserted)
			INSERT	[Reporting].[UserHistory]
				(
					[USERID],[EMAIL],[SURNAME],[NAME],[PATRONYMIC],[LOGIN],[INN],[DIVISION],
					[POSITION],[DEPARTMENT],[BANK_NFS],[NAME_NET],[FL_FIRED],[CREATED],
					[CREATOR], [CHANGED],[CHANGER]
				)
			SELECT	[ID],[EMAIL],[SURNAME],[NAME],[PATRONYMIC],[LOGIN],[INN],[DIVISION],
					[POSITION],[DEPARTMENT],[BANK_NFS],[NAME_NET],[FL_FIRED],[CREATED],
					[CREATOR], [CHANGED],[CHANGER]
			FROM	deleted;
		--	ЯКЩО UPDATE
		ELSE
		BEGIN
			INSERT	[Reporting].[UserHistory]
				(
					[USERID],[EMAIL],[SURNAME],[NAME],[PATRONYMIC],[LOGIN],[INN],[DIVISION],
					[POSITION],[DEPARTMENT],[BANK_NFS],[NAME_NET],[FL_FIRED],[CREATED],
					[CREATOR], [CHANGED],[CHANGER]
				)
			SELECT	[ID],[EMAIL],[SURNAME],[NAME],[PATRONYMIC],[LOGIN],[INN],[DIVISION],
					[POSITION],[DEPARTMENT],[BANK_NFS],[NAME_NET],[FL_FIRED],[CREATED],
					[CREATOR], [CHANGED],[CHANGER]
			FROM	deleted
			
			EXCEPT
			
			SELECT	[ID],[EMAIL],[SURNAME],[NAME],[PATRONYMIC],[LOGIN],[INN],[DIVISION],
					[POSITION],[DEPARTMENT],[BANK_NFS],[NAME_NET],[FL_FIRED],[CREATED],
					[CREATOR], [CHANGED],[CHANGER]
			FROM	inserted;

			UPDATE	T1
			SET		T1.CHANGED = GETDATE(),
					T1.CHANGER = USER
			FROM	[Reporting].[User] T1
			INNER JOIN	(
							SELECT	[ID],[EMAIL],[SURNAME],[NAME],[PATRONYMIC],[LOGIN],[INN],[DIVISION],
									[POSITION],[DEPARTMENT],[BANK_NFS],[NAME_NET],[FL_FIRED],[CREATED],
									[CREATOR], [CHANGED],[CHANGER]
							FROM	deleted
			
							EXCEPT
			
							SELECT	[ID],[EMAIL],[SURNAME],[NAME],[PATRONYMIC],[LOGIN],[INN],[DIVISION],
									[POSITION],[DEPARTMENT],[BANK_NFS],[NAME_NET],[FL_FIRED],[CREATED],
									[CREATOR], [CHANGED],[CHANGER]
							FROM	inserted
						) T2 ON T2.ID = T1.ID
		END

    END