CREATE TABLE [Reporting].[UserHistory]
(
	[ID] INT NOT NULL IDENTITY , 
    
	[USERID] INT NOT NULL, 
	[EMAIL] VARCHAR(100) NOT NULL,
	[SURNAME] VARCHAR(100) NOT NULL,
    [NAME] VARCHAR(100) NULL, 
	[PATRONYMIC] VARCHAR(100) NULL,
	[LOGIN] VARCHAR(100) NULL,
	[INN] VARCHAR(50) NULL,
	[DIVISION] VARCHAR(255) NULL,
	[POSITION] VARCHAR(100) NULL,
	[DEPARTMENT] VARCHAR(100) NULL,
	[BANK_NFS] VARCHAR(20) NULL,
	[NAME_NET] VARCHAR(100) NULL,

	[FL_FIRED] BIT NULL DEFAULT 0, 

    [CREATED] DATETIME NOT NULL DEFAULT GETDATE(), 
    [CREATOR] VARCHAR(100) NOT NULL DEFAULT USER, 
    [CHANGED] DATETIME NULL, 
    [CHANGER] VARCHAR(100) NULL, 

    [HCREATED] DATETIME NOT NULL DEFAULT GETDATE(), 
    CONSTRAINT [PK_REPORTING_USERHISTORY] PRIMARY KEY ([ID]), 

)
